apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cdi-pvc-fedora40
  namespace: default
  labels:
    app: containerized-data-importer
  annotations:
    cdi.kubevirt.io/storage.import.endpoint: "http://local-repo/Fedora-Cloud-Base-Generic.x86_64-40-1.14.qcow2" 
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
