apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: fedora-cloud-base-40
  namespace: default
spec:
  source:
    http:
      url: "http://local-repo/Fedora-Cloud-Base-Generic.x86_64-40-1.14.qcow2"
      #url: "http://fedora.c3sl.ufpr.br/linux/releases/40/Cloud/x86_64/images/Fedora-Cloud-Base-Generic.x86_64-40-1.14.qcow2"
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    storageClassName: fast-storage
