apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ubuntu-vm-1
  namespace: default
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: ubuntu-vm-1
        kubevirt.io/size: medium
        kubevirt.io/os: linux
    spec:
      domain:
        cpu:
          cores: 1
        devices:
          disks:
          - name: dv-disk0
            disk:
              bus: virtio
          - name: cloudinitdisk
            disk:
              bus: virtio
        resources:
          requests:
            memory: 1Gi
      volumes:
      - name: dv-disk0
        dataVolume:
          name: ubuntu-vm-1
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |
            #cloud-config
            hostname: ubuntu-vm-1
            ssh_pwauth: True
            disable_root: false
            chpasswd:
              list: |
                ubuntu:kubevirt
              expire: False

            write_files:
              - path: /home/ubuntu/fun-apt-script.sh
                permissions: '0755'
                content: |
                  #!/bin/bash
                  sudo apt update
                  sudo apt upgrade -y
                  sudo apt install cowsay sl fortune -y
                  sudo apt autoremove -y
                  sudo apt autoclean -y
                  sudo apt install openssh-server -y
                  sudo systemctl start ssh
                  sudo systemctl enable ssh
                  echo "Iniciando a diversão com apt! 🎉"
                  echo "Tudo pronto! Seu sistema está limpo e atualizado! ✨"
  dataVolumeTemplates:
  - metadata:
      name: ubuntu-vm-1
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: default-custom 
      source:
        http:
          url: "https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img"
