apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ubuntu-vm-1
  namespace: default
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: ubuntu-vm-1
        kubevirt.io/size: medium
        kubevirt.io/os: linux
    spec:
      domain:
        cpu:
          cores: 1
        devices:
          disks:
          - name: dv-disk0
            disk:
              bus: virtio
          - name: cloudinitdisk
            disk:
              bus: virtio
        resources:
          requests:
            memory: 1Gi
      volumes:
      - name: dv-disk0
        dataVolume:
          name: ubuntu-vm-1
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |
            #cloud-config
            hostname: ubuntu-vm
            ssh_pwauth: True
            disable_root: false
            password: kubevirt
            chpasswd:
              list: |
                ubuntu:kubevirt
              expire: False
  dataVolumeTemplates:
  - metadata:
      name: ubuntu-vm-1
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: default-custom
      source:
        pvc:
          name: ubuntu-cloud-base