kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: docker.io/kindest/node:v1.29.8
  extraMounts:
    - hostPath: /mnt/data
      containerPath: /mnt/data
- role: worker
  image: docker.io/kindest/node:v1.29.8
  extraMounts:
    - hostPath: /mnt/data
      containerPath: /mnt/data
