apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: default-custom
provisioner: kubevirt.io.hostpath-provisioner
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  storagePool: local